### ISSUE TITLE
Please don't use rar for Linux releases

### ISSUE THREAD

**Issue by probonopd** [moffa13/FilesEncrypt#1]
Please don't use rar for Linux releases, as rar is not common among Linux users and is not preinstalled on many distributions. Please use zip, tar.gz or tar.bz2. As for AppImages, they don't need to be inside an archive.

**Comment by moffa13** [comment]
Yes you are completely right I didn't even think rar wasn't installed by default. Next times I will release it as tar.gz archives or AppImages. Thank's for the advice !
